// <auto-generated />
using System;
using DuAn1_Nhom4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuAn1_Nhom4.Migrations
{
    [DbContext(typeof(QuanLyKhoHangQuanAoContext))]
    [Migration("20260331061549_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DuAn1_Nhom4.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuCt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuCt"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuCt")
                        .HasName("PK__ChiTietP__880CA1392BE51079");

                    b.HasIndex("MaCtsp");

                    b.HasIndex("MaPhieuNhap");

                    b.ToTable("ChiTietPhieuNhap", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.ChiTietSanPham", b =>
                {
                    b.Property<int>("MaCtsp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtsp"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DonGiaXuat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaKichThuoc")
                        .HasColumnType("int");

                    b.Property<int?>("MaMau")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCtsp")
                        .HasName("PK__ChiTietS__1E4FCECD5A111232");

                    b.HasIndex("MaKichThuoc");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietSanPham", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChucVu")
                        .HasName("PK__ChucVu__D4639533F8162856");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E37242659");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.KichThuoc", b =>
                {
                    b.Property<int>("MaKichThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKichThuoc"));

                    b.Property<string>("TenKichThuoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKichThuoc")
                        .HasName("PK__KichThuo__22BFD664D64780A0");

                    b.HasIndex(new[] { "TenKichThuoc" }, "UQ__KichThuo__9D0743DAA8DBD9B1")
                        .IsUnique();

                    b.ToTable("KichThuoc", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.MauSac", b =>
                {
                    b.Property<int>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMau"));

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaMau")
                        .HasName("PK__MauSac__3A5BBB7DF8DE72BE");

                    b.HasIndex(new[] { "TenMau" }, "UQ__MauSac__332F6A91EC332EE6")
                        .IsUnique();

                    b.ToTable("MauSac", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNcc"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc")
                        .HasName("PK__NhaCungC__3A185DEB777B5BE5");

                    b.HasIndex(new[] { "Email" }, "UQ__NhaCungC__A9D10534C377E567")
                        .IsUnique();

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__NhanVien__3214EC0783A2C830");

                    b.HasIndex("MaChucVu");

                    b.HasIndex(new[] { "Email" }, "UQ__NhanVien__A9D10534BD857E7A")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("NgayThanhToan")
                        .HasColumnType("date");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PK__PhieuNha__1470EF3B50CC6104");

                    b.HasIndex("MaNv");

                    b.ToTable("PhieuNhap", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.PhieuXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieuXuat")
                        .HasName("PK__PhieuXua__26C4B5A23E29C664");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("PhieuXuat", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.PhieuXuatChiTiet", b =>
                {
                    b.Property<int>("MaCt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCt"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    b.Property<int>("MaPhieuXuat")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCt")
                        .HasName("PK__PhieuXua__27258E74350C49F2");

                    b.HasIndex("MaCtsp");

                    b.HasIndex("MaPhieuXuat");

                    b.ToTable("PhieuXuatChiTiet", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<int?>("MaNcc")
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    b.Property<int?>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSP");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C94309B64");

                    b.HasIndex("MaNcc");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.TaiKhoanNhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("Id")
                        .HasName("PK__TaiKhoan__3214EC07A1B421AE");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TaiKhoan__55F68FC0CDD9E599")
                        .IsUnique();

                    b.HasIndex(new[] { "NhanVienId" }, "UQ__TaiKhoan__E27FD78B1F416C20")
                        .IsUnique();

                    b.ToTable("TaiKhoanNhanVien", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.ThuongHieu", b =>
                {
                    b.Property<int>("MaThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuongHieu"));

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThuongHieu")
                        .HasName("PK__ThuongHi__A3733E2CCB3EE93B");

                    b.HasIndex(new[] { "TenThuongHieu" }, "UQ__ThuongHi__98D6A83401D39344")
                        .IsUnique();

                    b.ToTable("ThuongHieu", (string)null);
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("DuAn1_Nhom4.Models.ChiTietSanPham", "MaCtspNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaCtsp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__MaCTS__628FA481");

                    b.HasOne("DuAn1_Nhom4.Models.PhieuNhap", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__MaPhi__619B8048");

                    b.Navigation("MaCtspNavigation");

                    b.Navigation("MaPhieuNhapNavigation");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("DuAn1_Nhom4.Models.KichThuoc", "MaKichThuocNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaKichThuoc")
                        .HasConstraintName("FK__ChiTietSa__MaKic__59063A47");

                    b.HasOne("DuAn1_Nhom4.Models.MauSac", "MaMauNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaMau")
                        .HasConstraintName("FK__ChiTietSa__MaMau__5812160E");

                    b.HasOne("DuAn1_Nhom4.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietSan__MaSP__571DF1D5");

                    b.Navigation("MaKichThuocNavigation");

                    b.Navigation("MaMauNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.NhanVien", b =>
                {
                    b.HasOne("DuAn1_Nhom4.Models.ChucVu", "MaChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK__NhanVien__MaChuc__3A81B327");

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.PhieuNhap", b =>
                {
                    b.HasOne("DuAn1_Nhom4.Models.NhanVien", "MaNvNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuNhap__MaNV__5CD6CB2B");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.PhieuXuat", b =>
                {
                    b.HasOne("DuAn1_Nhom4.Models.KhachHang", "MaKhNavigation")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuXuat__MaKH__66603565");

                    b.HasOne("DuAn1_Nhom4.Models.NhanVien", "MaNvNavigation")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuXuat__MaNV__6754599E");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.PhieuXuatChiTiet", b =>
                {
                    b.HasOne("DuAn1_Nhom4.Models.ChiTietSanPham", "MaCtspNavigation")
                        .WithMany("PhieuXuatChiTiets")
                        .HasForeignKey("MaCtsp")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuXuat__MaCTS__6D0D32F4");

                    b.HasOne("DuAn1_Nhom4.Models.PhieuXuat", "MaPhieuXuatNavigation")
                        .WithMany("PhieuXuatChiTiets")
                        .HasForeignKey("MaPhieuXuat")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuXuat__MaPhi__6C190EBB");

                    b.Navigation("MaCtspNavigation");

                    b.Navigation("MaPhieuXuatNavigation");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.SanPham", b =>
                {
                    b.HasOne("DuAn1_Nhom4.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK__SanPham__MaNCC__4BAC3F29");

                    b.HasOne("DuAn1_Nhom4.Models.ThuongHieu", "MaThuongHieuNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaThuongHieu")
                        .HasConstraintName("FK__SanPham__MaThuon__4AB81AF0");

                    b.Navigation("MaNccNavigation");

                    b.Navigation("MaThuongHieuNavigation");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.TaiKhoanNhanVien", b =>
                {
                    b.HasOne("DuAn1_Nhom4.Models.NhanVien", "NhanVien")
                        .WithOne("TaiKhoanNhanVien")
                        .HasForeignKey("DuAn1_Nhom4.Models.TaiKhoanNhanVien", "NhanVienId")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoanN__NhanV__403A8C7D");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.ChiTietSanPham", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("PhieuXuatChiTiets");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.KhachHang", b =>
                {
                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.KichThuoc", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.MauSac", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.NhaCungCap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.NhanVien", b =>
                {
                    b.Navigation("PhieuNhaps");

                    b.Navigation("PhieuXuats");

                    b.Navigation("TaiKhoanNhanVien");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.PhieuXuat", b =>
                {
                    b.Navigation("PhieuXuatChiTiets");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("DuAn1_Nhom4.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
